name: gemini_chat_app_tutorial
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_gemini: ^2.0.3
  image_picker: ^1.0.7
  dash_chat_2: ^0.0.20
  video_player: ^2.9.1
  flutter_tts: ^3.0.0
  speech_to_text: ^6.6.0
  animated_bottom_navigation_bar: ^1.0.0
  flutter_heatmap_calendar: ^1.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  provider: ^6.1.2
  adapters: ^0.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.jpg"

flutter:
  uses-material-design: true
assets:
  - assets/images/
